version: '3.7'

services:
  redisearch:
    image: redislabs/redisearch:2.0.0
    container_name: redisearch
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    network_mode: bridge