export SearchCommands

baremodule SearchCommands
    const NUMERIC = "NUMERIC"
    
    const CREATE_CMD = "FT.CREATE"
    const ALTER_CMD = "FT.ALTER"
    const SEARCH_CMD = "FT.SEARCH"
    const ADD_CMD = "FT.ADD"
    const ADDHASH_CMD = "FT.ADDHASH"
    const DROP_CMD = "FT.DROP"
    const EXPLAIN_CMD = "FT.EXPLAIN"
    const EXPLAINCLI_CMD = "FT.EXPLAINCLI"
    const DEL_CMD = "FT.DEL"
    const AGGREGATE_CMD = "FT.AGGREGATE"
    const CURSOR_CMD = "FT.CURSOR"
    const SPELLCHECK_CMD = "FT.SPELLCHECK"
    const DICT_ADD_CMD = "FT.DICTADD"
    const DICT_DEL_CMD = "FT.DICTDEL"
    const DICT_DUMP_CMD = "FT.DICTDUMP"
    const GET_CMD = "FT.GET"
    const MGET_CMD = "FT.MGET"
    const CONFIG_CMD = "FT.CONFIG"
    const TAGVALS_CMD = "FT.TAGVALS"
    const ALIAS_ADD_CMD = "FT.ALIASADD"
    const ALIAS_UPDATE_CMD = "FT.ALIASUPDATE"
    const ALIAS_DEL_CMD = "FT.ALIASDEL"
    const INFO_CMD = "FT.INFO"
    const SUGADD_COMMAND = "FT.SUGADD"
    const SUGDEL_COMMAND = "FT.SUGDEL"
    const SUGLEN_COMMAND = "FT.SUGLEN"
    const SUGGET_COMMAND = "FT.SUGGET"
    const SYNUPDATE_CMD = "FT.SYNUPDATE"
    const SYNDUMP_CMD = "FT.SYNDUMP"

    const NOOFFSETS = "NOOFFSETS"
    const NOFIELDS = "NOFIELDS"
    const STOPWORDS = "STOPWORDS"
    const WITHSCORES = "WITHSCORES"
    const FUZZY = "FUZZY"
    const WITHPAYLOADS = "WITHPAYLOADS"

    const NOHL = "NOHL"
    const NOFREQS = "NOFREQS"
    const MAXTEXTFIELDS = "MAXTEXTFIELDS"
    const TEMPORARY = "TEMPORARY"
    const SKIPINITIALSCAN = "SKIPINITIALSCAN"
end
