name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: DocTest
        run: |
          julia --project=docs -e '
            using Documenter: doctest
            using RediSearch
            doctest(RediSearch)'
      - name: Build and Deploy
        run: julia --project=docs docs/make.jl
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
